core/api/urls.py
from rest_framework.routers import DefaultRouter

from django.urls import include, path
from . import views


router = DefaultRouter()
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)
router.register('recipes', views.RecipeViewSet)
router.register('comments', views.CommentsViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('wishlist/', views.WishListView.as_view(), name='wishlist-api'),
    path('wishlist/create/', views.CreateOrUpdateWishList.as_view(),
         name='wishlist-create-api'),
    path('wishlist/items/', views.WishListItemsView.as_view(),
         name='wishlist-items-api'),
    path('recipes/<int:pk>/wishlist-toggle/',
         views.WishListToggleView.as_view(), name='wishlist-toggle-api'),
    path('recipes/<int:pk>/add-comment/',
         views.CommentsCreateAPIView.as_view(), name='add-comment-api'),
    path('recipes/<int:recipe_pk>/remove-comment/<int:comment_pk>/',
         views.CommentsDestroyAPIView.as_view(), name='remove-comment-api'),
]

core/urls.py
from django.urls import path, include
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('create-recipe/', CreateRecipeView.as_view(), name='create-recipe'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='detail'),
    path('update-recipe/<int:pk>/', RecipeUpdateView.as_view(), name='update-recipe'),
    path('delete-recipe/<int:pk>/', RecipeDeleteView.as_view(), name='delete-recipe'),
    path('add/<int:pk>/', UpdateIngredient.as_view(), name='add-ingredients'),
    path('remove/<int:recipe>/<int:ingredient>/', RemoveIngredient.as_view(), name='remove-ingredients'),
    path('recipe-collection/', RecipeCollectionListView.as_view(), name='recipe-collection-list'),
    path('recipe/<int:pk>/add-comment/', AddComment.as_view(), name='add-comment'),
    path('remove-comment/<int:pk>/', RemoveComment.as_view(), name='remove-comment'),
    path('likes/', Likes.as_view(), name='likes'),
    path('update-collections/', UpdateCollectionView.as_view(), name='update-collections'),
    path('contact/', ContactView.as_view(), name='contact-us'),


    path('api/', include('core.api.urls')),
    
]

culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('products.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path


from .views import *

app_name = 'products'

urlpatterns = [
    path('products/', ProductListView.as_view(), name="products"),

    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard/products/', DashboardProductListView.as_view(), name="dashboard-products-list"),
    path('dashboard/products/add/', ProductCreateView.as_view(), name="dashboard-product-add"),
    path('dashboard/products/update/<int:pk>/', ProductUpdateView.as_view(), name="dashboard-product-update"),
    path('dashboard/products/delete/<int:pk>/', ProductDeleteView.as_view(), name="dashboard-product-delete"),

    path('dashboard/raw_material/', RawMaterialListView.as_view(), name="dashboard-raw-material-list"),
    path('dashboard/raw_material/add/', RawMaterialCreateView.as_view(), name="dashboard-raw-material-add"),
    # path('dashboard/raw_material/update/<int:pk>/', RawMaterialUpdateView.as_view(), name="dashboard-raw-material-update"),

    path('dashboard/stock/', StockListView.as_view(), name="dashboard-stock-list"),
    path('dashboard/stock/add/', StockCreateView.as_view(), name="dashboard-stock-add"),
    path('dashboard/stock/update/<int:pk>/', StockUpdateView.as_view(), name="dashboard-stock-update"),
    path('dashboard/stock/delete/<int:pk>/', StockDeleteView.as_view(), name="dashboard-stock-delete"),

    path('dashboard/products/stock/', ProductStockListView.as_view(), name="dashboard-product-stock-list"),
    path('dashboard/products/stock/add/', ProductStockCreateView.as_view(), name="dashboard-product-stock-add"),

    path('get_unit/', get_unit, name="get_unit"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from users import views as user_views


app_name = 'users'


urlpatterns = [
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
    path('profile-update/<int:pk>/',
         user_views.ProfileUpdate.as_view(), name='update_profile'),
    path('activate/<uidb64>/<token>/',
         user_views.activate_account, name='activate'),
    path('password-change/', user_views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

core/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

class CarouselObjects(models.Model):
    img = models.ImageField(upload_to='pictures')
    img_text = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=False)

class Tags(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Ingredients(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Ingredients'


class Recipe(models.Model):
    UNIT_CHOICES = (
        ('teaspoon', 'Teaspoon'),
        ('tablespoon', 'Tablespoon'),
        ('unit', 'Unit'),
        ('add_to_taste', 'Add to taste'),
    )

    title = models.CharField(max_length=200)
    data_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tags, blank=True)
    ingredients = models.ManyToManyField(Ingredients, blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to='pictures', default='pictures/mypic.jpg')
    preparation_time = models.IntegerField(blank=True, null=True)
    calories = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    paid_recipe = models.BooleanField(default=False)
    unit = models.CharField(max_length=20, choices=UNIT_CHOICES, default='unit')
    qty = models.IntegerField(blank=True, null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:detail', args=[self.pk])

    def get_summary(self):
        return self.description[:100] + '...'

    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '/media/pictures/mypic.jpg'

    @property
    def comments(self):
        qs = Comments.objects.filter(recipe=self).order_by('-created')
        return qs

    def likes_count(self):
        return self.likes.all().count()

    
class RecipeCollection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recipe = models.ManyToManyField(Recipe)

    def __str__(self):
        return self.user.profile.first_name


class Comments(models.Model):
    comment = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

core/forms.py
from django import forms
from core.models import Recipe
from django_summernote.widgets import SummernoteInplaceWidget, SummernoteWidget


class RecipeForm(forms.ModelForm):
    description = forms.CharField(widget=SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px'}}))
    class Meta:
        model = Recipe
        fields = ('title', 'description', 'image')
        
    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

core/api/views.py
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from rest_framework.response import Response
from rest_framework import status
from rest_framework.mixins import ListModelMixin, CreateModelMixin, DestroyModelMixin
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly
from rest_framework.authentication import SessionAuthentication
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.decorators import action
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404


from .serializers import (
    TagSerializer,
    IngredientSerializer,
    RecipeSerializer,
    RecipeDetailSerializer,
    WishlistSerializer,
    WishlistDetailSerializer,
    CommentSerializer,
    RecipeImageSerialzer)
from ..models import Tags, Ingredients, Recipe, RecipeCollection, Comments
from .permissions import IsOwnerOrReadOnly


class BaseAttrViewSet(ListModelMixin, CreateModelMixin, GenericViewSet):
    authentication_classes = [SessionAuthentication, ]
    permission_classes = [IsAuthenticated, ]

    def perform_create(self, serializer):
        if serializer.is_valid():
            obj = serializer.validated_data.get('name')
            qs = self.queryset.filter(name=obj)
            if obj:
                if not qs.exists():
                    serializer.save(user=self.request.user)
                    return Response(serializer.data)
                else:
                    return Response(serializer.data)
            else:
                return Response(data={'message': 'Empty product_name'},
                                status=status.HTTP_400_BAD_REQUEST)


class TagViewSet(BaseAttrViewSet):
    queryset = Tags.objects.all()
    serializer_class = TagSerializer


class IngredientViewSet(BaseAttrViewSet):
    queryset = Ingredients.objects.all()
    serializer_class = IngredientSerializer


class RecipeViewSet(ModelViewSet):
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_serializer_class(self):
        if self.action == 'retrieve':
            return RecipeDetailSerializer
        if self.action == 'upload_image':
            return RecipeImageSerialzer
        return self.serializer_class

    @action(methods=['POST'], detail=True, url_path='upload_image')
    def upload_image(self, request, pk=None):
        recipe = self.get_object()
        serializer = self.get_serializer(recipe, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(
                serializer.data,
                status = status.HTTP_200_OK
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class WishListView(generics.ListAPIView):
    queryset = RecipeCollection.objects.all()
    serializer_class = WishlistSerializer
    permission_classes = [IsOwnerOrReadOnly, IsAuthenticated]

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)


class CreateOrUpdateWishList(generics.CreateAPIView):
    queryset = RecipeCollection.objects.all()
    serializer_class = WishlistSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class WishListItemsView(generics.RetrieveAPIView):
    serializer_class = WishlistDetailSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def get_object(self):
        obj = get_object_or_404(RecipeCollection, user=self.request.user)
        return obj


class WishListToggleView(APIView):
    authentication_classes = [SessionAuthentication, ]
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def get(self, request, **kwargs):
        recipe_obj = get_object_or_404(Recipe, pk=self.kwargs.get('pk'))
        wishlist, created = RecipeCollection.objects.get_or_create(
            user=self.request.user)
        updated = False
        in_wishlist = False
        if recipe_obj in wishlist.recipe.all():
            wishlist.recipe.remove(recipe_obj)
            in_wishlist = False
        else:
            wishlist.recipe.add(recipe_obj)
            in_wishlist = True
        updated = True
        data = {
            "recipe": recipe_obj.pk,
            "updated": updated,
            "in_wishlist": in_wishlist,
        }
        return Response(data)


class CommentsViewSet(ListModelMixin, CreateModelMixin, DestroyModelMixin, GenericViewSet):
    queryset = Comments.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def get_queryset(self):
        return self.queryset.filter(recipe=self.kwargs.get('pk'))


class CommentsCreateAPIView(generics.ListCreateAPIView):
    queryset = Comments.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def get_queryset(self):
        return self.queryset.filter(recipe=self.kwargs.get('pk'))

    def perform_create(self, serializer):
        recipe = get_object_or_404(Recipe, pk=self.kwargs.get('pk'))
        serializer.save(user=self.request.user, recipe=recipe)


class CommentsDestroyAPIView(generics.DestroyAPIView):
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def get_object(self):
        obj = get_object_or_404(Comments, pk=self.kwargs.get('comment_pk'))
        return obj

core/templates/core/_like_snippet.html
{% if user.is_authenticated %}
<form method="POST">
    {%csrf_token%}
    
    {% if request.user in object.likes.all %}
    <button id="likes" value="{{object.id}}" class="btn btn-outline-danger mt-3">Unlike</button>
    {% else %}
    <button id="likes" value="{{object.id}}" class="btn btn-outline-info mt-3">Like</button>
    {% endif %}
    <span class="btn mt-3">Likes: {{object.likes_count}}</span>
</form>
{% endif %}

core/templates/core/_post.html
<div class="card mt-3 shadow-sm p-3 mb-3 bg-white rounded">
    <div class="row no-gutters">
        <div class="col-md-4">
            <a href="{% url 'core:detail' object.id %}"><img src="{{object.get_image_url}}" class="card-img"
                    alt="..."></a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{object.title | capfirst}}</h5>
                <p class="card-text">{{object.get_summary | safe | capfirst}}</p>
                <p class="card-text"><small class="text-muted">Created by: <span><a
                                href="{% url 'users:profile' %}">{{object.user.profile.first_name}}
                                {{object.user.profile.last_name}}</a></span> at
                        {{object.data_created | date:'d M Y'}}</small></p>
            </div>
        </div>
    </div>
</div>

core/templates/core/_update_collections.html
{% if user.is_authenticated %}
<form method="POST">
    {%csrf_token%}
    {% if is_collection %}
    <button type="submit" id="add-to-collections" value="{{ object.id }}" class="btn btn-outline-danger mt-3">Remove from
Collections</button>
    {%else%}
    <button type="submit" id="add-to-collections" value="{{ object.id }}" class="btn btn-outline-info mt-3">Add To
        My Collections</button>
    {%endif%}
</form>
{%endif%}

core/templates/core/contact.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form>
    <div class="contactForm">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <input type="text" class="form-control" name="first_name" placeholder="First Name">
            </div>
            <div class="col-md-4 offset-md-4">
                <input type="text" class="form-control" name="last_name" placeholder="Last Name">
            </div>
            <div class="col-md-4 offset-md-4">
                <input type="text" class="form-control" name="email" placeholder="someone@example.com">
            </div>
            <div class="col-md-4 offset-md-4">
                <textarea type="text" class="form-control" name="first_name" placeholder="Write to us..."></textarea>
            </div>
            <div class="col-md-4 offset-md-4">
                <button type="button" class="btn btn-block">Submit</button>
            </div>
        </div>

    </div>
</form>

{% endblock %}

core/templates/core/form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{form | crispy }}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

core/templates/core/home.html
{% extends 'users/base.html' %}
{% block body %}

<div class="container">
    <div class="row">

        <div class="col-md-4 order-md-1 mb-4">

            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <div class="row">
                    <div class="col-md-8 offset-md-2 mt-4 mb-4">
                        <img src="{{user.profile.image.url}}" class="rounded-circle card-img-top">
                    </div>
                </div>
                
                <div class="card-body">
                    <h5 class="card-title text-center">{{user.profile.first_name}} {{user.profile.last_name}}</h5>
                    <p class="text-center">{{user.profile.location}}</p>
                </div>

            </div>

        </div>

        <div class="col-md-8 order-md-2">
            
            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <!-- <div class="row no-gutters">
                    <div class="col-md-4">
                        
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{object.title | capfirst}}</h5>
                            <p class="card-text">{{object.get_summary | capfirst}}</p>
                            <p class="card-text"><small class="text-muted">Created {{object.data_created}}</small></p>
                        </div>
                    </div>
                </div> -->
            <h4>Profile Summary</h4>
            <hr>
            <div>
            <h5>About Me</h5>
            <p>{{user.profile.about_me}}</p>
            </div>
            <div>
                <h5>Email</h5>
                <p>{{user.email}}</p>
            </div>

            </div>
           
        </div>

    </div>
</div>



{% endblock %}

core/templates/core/index.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}

{% include 'core/inner-header.html' %}

<div class="container">
    <div class="headingDiv">
        <h4 class="headingText">Our Products</h4>
        <a class="viewAll" href="{% url 'products:products' %}">View all</a>
    </div>
    <div class="row">
        {% for item in item_list %}
        <div class="col-md-2 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{{item.image.url}}" />
                <div class="card-footer prodFooter">
                    <h5>{{item.product}}</h5>
                    <p>Price: {{item.price_after_tax}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr/>

    <h4 class="headingText">Browse Categories</h4>
    <p>We offer a range of products from Breads to Cakes. Choose your favourite Category.</p>

    <div class="row pb-3">
        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_cake.jpg'%}" />
                <div class="card-footer">
                    <h5>Cakes</h5>
                    <p>Choose from a wide variety of Cakes</p>
                </div>
                <a href="{% url 'products:products' %}?category__category__icontains=cake" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>

        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_cookies.jpg'%}" />
                <div class="card-footer">
                    <h5>Cookies</h5>
                    <p>Chocolate, Coconut we got 'em all</p>
                </div>
                <a href="{% url 'products:products' %}?category__category__icontains=cookies" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>

        <div class="col-md-4 col-sm-3 p-3">
            <div class="card h-100">
                <img class="card-img-top" src="{%static 'pictures/default_breads.jpg'%}" />
                <div class="card-footer">
                    <h5>Breads</h5>
                    <p>Fresh, soft and crispy at the same time</p>
                </div>
                <a href="{% url 'products:products' %}?category__category__icontains=bread" class="btn btn-block btn-outline-orange">Browse...</a>
            </div>
            
        </div>
    </div>
</div>

{% endblock body %}

core/templates/core/inner-header.html
<div id="carouselIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for img in carousel_obj%}
    <li data-target="#carouselIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for img in carousel_obj%}
    <div class="carousel-item carouselImg {% if forloop.counter == 1 %}active{%endif%}">
      <img class="d-block w-100" src="{{img.img.url}}" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{img.img_text}}</h5>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script>
  $('.carousel').carousel({
    interval: 2000
  })
</script>

core/templates/core/recipe_confirm_delete.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-4 offset-md-4">
            <div class="card shadow mt-4 bg-white rounded">
                <div class="card-body">
                    <h4>Are you sure you want to delete {{obj.title}}</h4>
                    <form method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

core/templates/core/recipe_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2 mt-4">
      <div class="card shadow">
        <div class="card-header  text-white">
          <div class="card-title">
            <h5>Add Recipe</h5>
          </div>
        </div>
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
            <div>
              {% csrf_token %}
              {{ form | crispy }}
            </div>

            <div class="row">
              <div class="col-md-6">
                <label for="recipe-tag">Tags</label>
                <div class="form-group form-inline tag-wrap">
                  <div class="input-group">
                    <input type="text" class="form-control mb-3" name="tag" id="recipe-tag" />
                    <span class="input-group-append">
                      <button type="submit" class="form-control btn btn-outline-info add-tag" id="add-tag"><i
                          class="fas fa-plus"></i></button>
                    </span>
                  </div>
                </div>
              </div>


              <div class="col-md-6">
                <label for="recipe-ingredient">Ingredients</label>
                <div class="form-group form-inline ingredient-wrap">
                  <div class="input-group">
                    <input type="text" class="form-control mb-3" name="ingredient" id="recipe-ingredient" />
                    <span class="input-group-append">
                      <button type="submit" class="form-control btn btn-outline-info add-ingredient mb-3"
                        id="add-ingredients"><i class="fas fa-plus"></i></button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <button type="submit" class="btn btn-block btn-outline-info float-right">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/core/recipe_update_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2 mt-4">
            <div class="card">
                <div class="card-header  text-white">
                    <div class="card-title">
                        <h5>Update Recipe</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-outline-info btn-block mt-3 mb-3">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/templates/core/update.html
{% extends 'users/base.html' %}

{% block body %}

<div class="container mt-3 mb-3">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h4>Remove Ingredients</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" id="remove-tab-div">
                    <ul id="remove-block">
                        {% for ingredient in recipe.ingredients.all %}
                        <li>{{ingredient}}<span>
                                <a href="{% url 'core:remove-ingredients' recipe.id ingredient.id %}"
                                    id="{{ingredient.id}}" class="btn"><i class="fas fa-trash"></i></a></span></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Add Ingredients</h4>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group form-inline ingredient-wrap">
                    <div class="input-group">
                        <input type="text" class="form-control mb-3" name="ingredient" id="recipe-ingredient" />
                        <span class="input-group-append">
                            <a href="" class="form-control btn btn-outline-info add-ingredient mb-3 mr-3"
                                id="add-ingredients"><i class="fas fa-plus"></i></a>
                        </span>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

    </div>
</div>

{% endblock %}